AllCops:
  Exclude:
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Style/Documentation:
  Exclude:
    - 'db/migrate/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false